### ISSUE TITLE
https://github.com/CarmenJi/alluxio/tree/smallfix

### ISSUE THREAD

**Issue by CarmenJi** [PasaLab/MR-Course-Assignments#57] opened 2018-10-23 08:31 UTC
(Your NJUID here)

MF1833031

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/284

(Your PR link here)

https://github.com/CarmenJi/alluxio/tree/smallfix

**Comment by newnius** [comment] 2018-10-23 08:34
Invalid PR link

Please **RTFM**

**Comment by newnius** [comment] 2018-10-24 09:51
Duplicate of #58

**Closed** 2018-10-24 09:59 UTC
